accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'  # تحديد اسم التطبيق (namespace)



urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),
]

job/urls.py
from django.urls import path
from . import views

app_name = 'job'  # تحديد اسم التطبيق (namespace)



urlpatterns = [
    path('', views.job_list, name='job_list'),  # URL لعرض قائمة الوظائف
    path('add', views.add_job, name='add_job'),
    path('<slug:slug>/', views.job_details,name='job_details'),  # URL لتفاصيل الوظيفة
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('', include('mian.urls', namespace='index')),
    path('jobs/', include('job.urls', namespace='jobs')),
    path('contact-us/', include('contact.urls', namespace='contact')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    city = models.ForeignKey('City', related_name='user_city', on_delete=models.CASCADE, blank=True, null=True)
    phone_number = models.CharField(max_length=15)
    image = models.ImageField(upload_to='profile/')

    def __str__(self):
        return str(self.user)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

class City(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self) -> str:
        return self.name

accounts/forms.py
# from attr import fields
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

User = get_user_model()


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user']

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login
from .forms import SignupForm, ProfileForm, UserForm
from .models import Profile
from django.contrib.auth.decorators import login_required



def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/')
    else:
        form = SignupForm()
    context = {'form':form}
    return render(request, 'registration/signup.html', context)


def profile(request):
    profile = Profile.objects.get(user=request.user)
    return render(request, 'accounts/profile.html', {'profile': profile})


@login_required
def profile_edit(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form = profile_form.save(commit=False)
            profile_form.user = request.user
            profile_form.save()
            return redirect('/accounts/profile')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=profile)
    return render(request, 'accounts/profile_edit.html', {'profile_form': profile_form, 'user_form': user_form})

accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}



    {% block content %}
        <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->
    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Profile Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>name: <span>{{profile}}</span></li>
                                <li>email: <span>{{profile.user.email}} </span></li>
                                <li>phone: <span>{{profile.phone_number}}</span></li>
                                <li>address: <span>{{profile.city}}</span></li>
                                {% comment %} <li>Job Nature: <span> {{job.job_type}}</span></li> {% endcomment %}
                            </ul>
                                <a class="boxed-btn3 w-100" href="{% url 'accounts:profile_edit' %}">edit profile</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock content %}

accounts/templates/accounts/profile_edit.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}



    {% block content %}
        <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
        </div>
    </div>
    <!--/ bradcam_area  -->
    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4>edit profile</h4>
                        <form method='POST' class="form" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form user_form %}
                            {% bootstrap_form profile_form %}
                            {% buttons %}
                                <button class="boxed-btn3 w-100" type="submit">confirm edits</button>
                            {% endbuttons %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock content %}